// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantCare.Api.Data;

#nullable disable

namespace PlantCare.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919210315_AddRooms")]
    partial class AddRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PlantCare.Api.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "Type", "SentAt");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomWateringIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastWateredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlantProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlantProfileId");

                    b.HasIndex("RoomId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CareTips")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultWateringIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HumidityNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LightRequirement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .IsUnique();

                    b.ToTable("PlantProfiles");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PlantCare.Api.Models.WateringLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("WateredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "WateredAt");

                    b.ToTable("WateringLogs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.NotificationLog", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.HasOne("PlantCare.Api.Models.PlantProfile", "PlantProfile")
                        .WithMany("Plants")
                        .HasForeignKey("PlantProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlantCare.Api.Models.Room", "Room")
                        .WithMany("Plants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlantProfile");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PlantCare.Api.Models.WateringLog", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany("WateringLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.Navigation("NotificationLogs");

                    b.Navigation("WateringLogs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfile", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Room", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
