// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantCare.Api.Data;

#nullable disable

namespace PlantCare.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920125116_AddProfileTranslations")]
    partial class AddProfileTranslations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PlantCare.Api.Models.CareTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDoneAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ReduceInWinter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "Type")
                        .IsUnique();

                    b.ToTable("CareTasks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.CareTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmountMilliliters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DoneAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CareTaskId", "DoneAt");

                    b.ToTable("CareTaskLogs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.JobRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RanAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SentDigests")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkippedDuplicates")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RanAt");

                    b.ToTable("JobRuns");
                });

            modelBuilder.Entity("PlantCare.Api.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "EntryDate");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("PlantCare.Api.Models.NotificationDigest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverdueCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.ToTable("NotificationDigests");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PlantProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PotSizeCm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PropagatedFrom")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoilMix")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantProfileId");

                    b.HasIndex("RoomId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "CreatedAt");

                    b.ToTable("PlantNotes");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CareTips")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultReduceInWinter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultWateringIntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiagnosisChecklist")
                        .HasColumnType("TEXT");

                    b.Property<string>("HumidityNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LightRequirement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ToxicToChildren")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ToxicToPets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .IsUnique();

                    b.ToTable("PlantProfiles");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfileTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CareTips")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosisChecklist")
                        .HasColumnType("TEXT");

                    b.Property<string>("HumidityNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlantProfileId", "Language")
                        .IsUnique();

                    b.ToTable("PlantProfileTranslations");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Humidity")
                        .HasColumnType("TEXT");

                    b.Property<string>("LightExposure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Orientation")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TemperatureCelsius")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PlantCare.Api.Models.CareTask", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany("CareTasks")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.CareTaskLog", b =>
                {
                    b.HasOne("PlantCare.Api.Models.CareTask", "CareTask")
                        .WithMany("Logs")
                        .HasForeignKey("CareTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareTask");
                });

            modelBuilder.Entity("PlantCare.Api.Models.JournalEntry", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.HasOne("PlantCare.Api.Models.PlantProfile", "PlantProfile")
                        .WithMany("Plants")
                        .HasForeignKey("PlantProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlantCare.Api.Models.Room", "Room")
                        .WithMany("Plants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlantProfile");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantNote", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfileTranslation", b =>
                {
                    b.HasOne("PlantCare.Api.Models.PlantProfile", "PlantProfile")
                        .WithMany("Translations")
                        .HasForeignKey("PlantProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantProfile");
                });

            modelBuilder.Entity("PlantCare.Api.Models.CareTask", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.Navigation("CareTasks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfile", b =>
                {
                    b.Navigation("Plants");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Room", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
