// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantCare.Api.Data;

#nullable disable

namespace PlantCare.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920110246_AddJobRunLogs")]
    partial class AddJobRunLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PlantCare.Api.Models.CareTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("IntervalDays");

                    b.Property<DateTime?>("LastDoneAt");

                    b.Property<int>("PlantId");

                    b.Property<bool?>("ReduceInWinter");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "Type")
                        .IsUnique();

                    b.ToTable("CareTasks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.CareTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AmountMilliliters");

                    b.Property<int>("CareTaskId");

                    b.Property<DateTime>("DoneAt");

                    b.Property<string>("Method");

                    b.Property<string>("Note");

                    b.HasKey("Id");

                    b.HasIndex("CareTaskId", "DoneAt");

                    b.ToTable("CareTaskLogs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.JobRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Failed");

                    b.Property<string>("Outcome")
                        .IsRequired();

                    b.Property<DateTime>("RanAt");

                    b.Property<int>("SentDigests");

                    b.Property<int>("SkippedDuplicates");

                    b.HasKey("Id");

                    b.HasIndex("RanAt");

                    b.ToTable("JobRuns");
                });

            modelBuilder.Entity("PlantCare.Api.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EntryDate");

                    b.Property<string>("PhotoUrl");

                    b.Property<int>("PlantId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "EntryDate");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("PlantCare.Api.Models.NotificationDigest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OverdueCount");

                    b.Property<int>("PlantCount");

                    b.Property<int>("Priority");

                    b.Property<DateTime>("SentAt");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.ToTable("NotificationDigests");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AcquiredDate");

                    b.Property<string>("NickName")
                        .IsRequired();

                    b.Property<bool>("NotifyEnabled");

                    b.Property<string>("PhotoUrl");

                    b.Property<int?>("PlantProfileId");

                    b.Property<int?>("PotSizeCm");

                    b.Property<string>("PropagatedFrom");

                    b.Property<int?>("RoomId");

                    b.Property<DateTime?>("SnoozedUntil");

                    b.Property<string>("SoilMix");

                    b.HasKey("Id");

                    b.HasIndex("PlantProfileId");

                    b.HasIndex("RoomId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PlantId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "CreatedAt");

                    b.ToTable("PlantNotes");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CareTips")
                        .IsRequired();

                    b.Property<string>("CommonName")
                        .IsRequired();

                    b.Property<bool>("DefaultReduceInWinter");

                    b.Property<int>("DefaultWateringIntervalDays");

                    b.Property<string>("DiagnosisChecklist");

                    b.Property<string>("HumidityNotes")
                        .IsRequired();

                    b.Property<string>("LightRequirement")
                        .IsRequired();

                    b.Property<string>("ScientificName");

                    b.Property<bool>("ToxicToChildren");

                    b.Property<bool>("ToxicToPets");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .IsUnique();

                    b.ToTable("PlantProfiles");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Humidity");

                    b.Property<string>("LightExposure");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Orientation");

                    b.Property<int?>("TemperatureCelsius");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PlantCare.Api.Models.CareTask", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany("CareTasks")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.CareTaskLog", b =>
                {
                    b.HasOne("PlantCare.Api.Models.CareTask", "CareTask")
                        .WithMany("Logs")
                        .HasForeignKey("CareTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareTask");
                });

            modelBuilder.Entity("PlantCare.Api.Models.JournalEntry", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.HasOne("PlantCare.Api.Models.PlantProfile", "PlantProfile")
                        .WithMany("Plants")
                        .HasForeignKey("PlantProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlantCare.Api.Models.Room", "Room")
                        .WithMany("Plants")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlantProfile");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantNote", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.CareTask", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.Navigation("CareTasks");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfile", b =>
                {
                    b.Navigation("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Room", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
