// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantCare.Api.Data;

#nullable disable

namespace PlantCare.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918142916_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PlantCare.Api.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlantId");

                    b.Property<DateTime>("SentAt");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "Type", "SentAt");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AcquiredDate");

                    b.Property<int?>("CustomWateringIntervalDays");

                    b.Property<DateTime?>("LastWateredAt");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("NickName")
                        .IsRequired();

                    b.Property<string>("PhotoUrl");

                    b.Property<int?>("PlantProfileId");

                    b.HasKey("Id");

                    b.HasIndex("PlantProfileId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CareTips")
                        .IsRequired();

                    b.Property<string>("CommonName")
                        .IsRequired();

                    b.Property<int>("DefaultWateringIntervalDays");

                    b.Property<string>("HumidityNotes")
                        .IsRequired();

                    b.Property<string>("LightRequirement")
                        .IsRequired();

                    b.Property<string>("ScientificName");

                    b.HasKey("Id");

                    b.HasIndex("CommonName")
                        .IsUnique();

                    b.ToTable("PlantProfiles");
                });

            modelBuilder.Entity("PlantCare.Api.Models.WateringLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note");

                    b.Property<int>("PlantId");

                    b.Property<DateTime>("WateredAt");

                    b.HasKey("Id");

                    b.HasIndex("PlantId", "WateredAt");

                    b.ToTable("WateringLogs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.NotificationLog", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.HasOne("PlantCare.Api.Models.PlantProfile", "PlantProfile")
                        .WithMany("Plants")
                        .HasForeignKey("PlantProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PlantProfile");
                });

            modelBuilder.Entity("PlantCare.Api.Models.WateringLog", b =>
                {
                    b.HasOne("PlantCare.Api.Models.Plant", "Plant")
                        .WithMany("WateringLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("PlantCare.Api.Models.Plant", b =>
                {
                    b.Navigation("NotificationLogs");

                    b.Navigation("WateringLogs");
                });

            modelBuilder.Entity("PlantCare.Api.Models.PlantProfile", b =>
                {
                    b.Navigation("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
